### ISSUE TITLE
Future Enhancements

### ISSUE THREAD

**Issue by zz85** [zz85/mrdoobapproves#1]
Expanding from commit message  https://github.com/zz85/mrdoobapproves/commit/09925d95885254302475e1544840a84af50f9805 here are a couple ideas to improve this tool:
## release 1.0 !!!
- [x] add drop-in good / bad examples (somewhat fullfilled by #8)
- [x] ~~highlight errors~~
- [x] code syntax highlighting (eg. ~~Ace Editor / Orion /~~ Code Mirror) #7
- [x] open file via File API / drag-and-drop source file #24 
- [x] auto-format / auto-correct (#3) - still wip
- [x] check while typing (#2)
- [x] ~~list errors in an error list (IDE style)~~ lint messages in gutter #11
- [x] ~~use npm or jspm to include jscs bundles~~ use bower / webpack if necessary. #30
- [x] show diff panel when auto formatting (#21)
- [x] run auto-format on its own code (#33)

Feel free to make suggestions or PRs :D

**Comment by gero3** [comment]
@zz85 
Do you mind using an experimental version of autoformatter?? Other wise I could update [formatter](https://github.com/gero3/node-jscs/tree/formatter) to make it work with this version. I tested the formatter before on three.min.js and there were only some minor issues left.

**Comment by zz85** [comment]
yes, i wouldn't mind. i also realize there have been some recent changes in jscs that some rules aren't working eg spaces between parenthesis.

@gero3, which is your latest working copy right now?

**Comment by gero3** [comment]
A local version for the moment but the one I linked to shouldn't be far behind. It still has a problem with whitespacing tough. I'll see if I can make a version today.

A small suggestion would to also have diff library then, to actually highlight the proposed changes.

For systax highlighting, I wouldn't use anything fancy, [Prettify](https://github.com/mrdoob/three.js/tree/master/docs/prettify) should be good enough, I think.

**Comment by zz85** [comment]
Diffing sounds like a good idea. I'll take a look at prettify but I was
thinking CodeMirror is a good candidate as it supports warning messages in
the gutter like any good editor/ide

**Comment by gero3** [comment]
Dropping source files already works in codemirror.

**Comment by zz85** [comment]
@gero3 nice observation! it relatively easy for me to add a "click to browse" button too though.

**Comment by zz85** [comment]
Happy new year all! I'm actually pretty satisfied with where things are right now - given this was started 3 days ago, we already have 14 PRs merged, thanks largely to the efforts of @gero3 (and probably this "PR-driven-development").

There are only a couple more checkboxes here to strike off, and I think we should stamp a v1.0 for the new year and probably move on to do other greater stuff. Just before we do that, there's just a couple more things
1. adding the browse/open file feature
2. getting #19 and #20 resolved
3. bundling / minifying the js file to make loads faster
4. blog about this

i'll work on 1,2,4 and we should soon be able to give ourselves a pat on the back and call it a day (until #22). :grinning:

**Comment by gero3** [comment]
Happy new year :tada:. I fixed issues #19 and #20 in #23. 
I'll see if I can make time today to strike off bundling / minifying the js file to make loads faster.

**Comment by zz85** [comment]
thanks... and oops i think i mean't 1, 3, 4 just now. also one more thing which we should do is run code-formatter on our code to clean them out :)

**Comment by zz85** [comment]
Closing with [blog post](http://www.lab4games.net/zz85/blog/2015/01/25/mrdoob-approves-a-javascript-codestyle-editor-validator-formatter-project/) and [release 1.0](https://github.com/zz85/mrdoobapproves/releases/tag/v1.0.0) :)
